image:
  repository: myacr123.azurecr.io/order-service
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  port: 8080
  type: ClusterIP

env:
  SPRING_PROFILES_ACTIVE: "prod"

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

health:
  livenessPath: "/actuator/health/liveness"
  readinessPath: "/actuator/health/readiness"
