replicaCount: 2

image:
  repository: myacr.azurecr.io/application-service
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  port: 8080

env:
  SPRING_PROFILES_ACTIVE: "prod"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

health:
  livenessPath: "/actuator/health/liveness"
  readinessPath: "/actuator/health/readiness"

imagePullSecrets: []
nodeSelector: {}
tolerations: []
affinity: {}
